# .github/workflows/snake.yml
name: Generate Contribution Snake

# Allow the workflow to push commits back to the repo
permissions:
  contents: write

on:
  schedule:
    # every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Ensure dist/ exists
      - name: Prepare dist folder
        run: mkdir -p dist

      # 3) Generate all snake outputs at once
      - name: Generate snake assets
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4) Commit & push the generated files back to main
      - name: Commit and push snake assets
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "chore: update contribution snake"
          file_pattern: "dist/**"
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
